language: java

sudo: false

services:
- postgresql
before_script:
- psql -c 'create database ci_test_database;' -U postgres

matrix:
  include:
  - script:
    - ci/ci-test.sh
    - bash <(curl -s https://codecov.io/bash)
    jdk: oraclejdk11
  - script:	
    - ci/ci-test.sh	
    jdk: openjdk12
  - script:	
    - ci/ci-test.sh	
    jdk: openjdk10

cache:
  directories:
  - $HOME/.gradle/caches
