language: java

sudo: false

matrix:
  include:
  - script:
    - ci/ci-test.sh
    jdk: oraclejdk10
  - script:
    - ci/ci-test.sh
    - bash <(curl -s https://codecov.io/bash)
    jdk: oraclejdk11

cache:
  directories:
  - $HOME/.gradle/caches